---
- name: Ensure dedicated oakestra-ansible directory exists
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory

- name: Fetch all tags from remote
  block:
    - ansible.builtin.command:
        cmd: git fetch --tags --force
        chdir: "{{ path }}"
  ansible.builtin.command:
    cmd: git fetch --tags
    chdir: "{{ path }}"
  ignore_errors: yes  


- name: Ensure {{ repo }} Repo is cloned
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ path }}"
    version: "{{ branch }}"
    force: true