---
- name: Ensure dedicated oakestra-ansible directory exists
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory

- name: Fetch all tags from remote
  cmd: git fetch --tags --force #"{{ repo }}"
  path: "{{ path }}"


- name: Ensure {{ repo }} Repo is cloned
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ path }}"
    version: "{{ branch }}"
    force: true