- name: Retrieve local hostname list
  set_fact:
    workers_hostname: >
      {{ hostvars | dict2items
      | selectattr('value.local_hostname', 'defined')
      | map(attribute='value.local_hostname.stdout')
      | list }}

- name: Available hostnames display
  debug:
    msg: "Available hostnames: {{ workers_hostname }}"

- name: Print group_clusters
  debug:
    msg: "group_clusters: {{ group_clusters }}"

- name: Print group_root
  debug:
    msg: "group_root: {{ group_root }}"

- name: Set topology_desc JSON string
  set_fact:
    topology_desc_json: "{{ topology_desc | to_nice_json }}"

- name: Set workers list JSON string
  set_fact:
    workers_json: "{{ workers_hostname | list }}"

- name: Save topology_desc to a file
  copy:
    content: "{{ topology_desc_json }}"
    dest: "/tmp/topology_desc.json"

- name: Upgrade pip to the latest version
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install Python packages from requirements.txt
  pip:
    requirements: ./utils/topology-app-deploy/requirements.txt
    executable: /usr/bin/pip3
    chdir: ..
