---
- name: (1DOC Topology) - Retrieve hostnames of workers
  hosts: "{{ group_1doc }}"
  gather_facts: false
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

- name: (1DOC Topology) - App Deploy
  hosts: localhost
  roles:
    - role: topology-app-deploy
      vars:
        local_hostname: "{{ local_hostname }}"
        group_root_full: "{{ group_1doc }}"
        group_clusters_full: "{{ group_1doc }}"
        topology_desc: "{{ topology_desc }}"
      when: deploy_1doc and not together_root_cluster

- name: (Full Topology) - Retrieve hostnames of workers
  hosts: "{{ group_workers_full}}"
  gather_facts: false
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

- name: (Full Topology) - App Deploy
  hosts: localhost
  roles:
    - role: topology-app-deploy
      vars:
        local_hostname: "{{ local_hostname }}"
        group_root_full: "{{ group_root_full}}"
        group_clusters_full: "{{ group_clusters_full }}"
        topology_desc: "{{ topology_desc }}"
      when: not deploy_1doc and not together_root_cluster
