---
- name: (1DOC Topology) - Retrieve hostnames of workers
  hosts: "{{ group_1doc }}"
  gather_facts: true
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

