- name: Execute 1DOC template if one_doc_enabled is true
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fail if deploy_1doc is false
      fail:
        msg: "Deployment is skipped because deploy_1doc is false."
      when: not deploy_1doc

- name: Deploy components for 1DOC topology
  hosts: "{{ group_1doc }}"
  gather_facts: false
  roles:
    - ensure-oakestra-repo-is-cloned
    - start-1-doc
  vars:
    params: "-f run-a-cluster/override-alpha-versions.yaml"
    path: "{{ oak_repo_path }}"
    repo: "{{ oak_repo_link }}"
    branch: "{{ oak_repo_version }}"
