---
- name: Execute 1DOC template if one_doc_enabled is true
  hosts: localhost
  gather_facts: false
  roles:
    - ensure-oakestra-repo-is-cloned
    - start-1-doc
  vars:
    params: "-f run-a-cluster/override-alpha-versions.yaml"
    path: "{{ oak_repo_path }}"
    repo: "{{ oak_repo_link }}"
    branch: "{{ oak_repo_version }}"

  tasks:
    - name: Print group_1doc
      debug:
        var: group_1doc
        

