- name: Job Template 2 Playbook
  hosts: localhost
  tasks:
    - name: Use data from Job Template 1
      debug:
        msg: "Data from Job Template 1: {{ topology_desc }}"

    - name: Parse JSON input
      set_fact:
        topology: "{{ topology_desc | from_json }}"

    - name: Check if topology is valid
      fail:
        msg: "Topology is not valid. Deployment cannot proceed."
      when: not topology_validity

    - name: Print topology
      debug:
        var: topology

    - name: Calculate required number of VMs
      set_fact:
        num_clusters: "{{ topology.topology_descriptor.cluster_list | length }}"
        num_nodes: "{{ topology.topology_descriptor.cluster_list | map(attribute='number_of_nodes') | sum }}"
        one_doc_enabled: "{{ topology.topology_descriptor.one_doc_enabled | bool }}"
        together_root_cluster: "{{ topology.topology_descriptor.together_root_cluster | bool }}"

    - name: Calculate requested_vms based on one_doc_enabled and together_root_cluster
      set_fact:
        requested_vms: >-
          {%- if one_doc_enabled -%}
          1
          {%- elif together_root_cluster -%}
          {{ (1 | int) + (num_nodes | int) }}
          {%- else -%}
          {{ (1 | int) + (num_clusters | int) + (num_nodes | int) }}
          {%- endif -%}

    - name: Set workflow data
      set_stats:
        data:
          requested_vms: "{{ requested_vms }}"

- name: Check hosts for OAK_STATUS
  hosts: all
  gather_facts: false
  tasks:
    - name: Check OAK_STATUS environment variable
      shell: |
        echo $OAK_STATUS
      register: oak_status

    - name: Set host availability
      set_fact:
        host_available: "{{ oak_status.stdout != 'busy' }}"
      when: oak_status.stdout is defined

    - name: Set host availability if OAK_STATUS is not set
      set_fact:
        host_available: true
      when: oak_status.stdout is not defined

    - name: Add available hosts to a list
      set_fact:
        available_hosts: "{{ available_hosts | default([]) + [inventory_hostname] }}"
      when: host_available
      delegate_facts: true

- name: Verify enough hosts are available
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather available hosts from all hosts
      set_fact:
        available_hosts: "{{ hostvars | dict2items | selectattr('value.host_available', 'defined') | selectattr('value.host_available', 'eq', True) | map(attribute='key') | list }}"

    - name: Print available hosts
      debug:
        msg: "Available hosts: {{ available_hosts }}"

    - name: Print requested_vms
      debug:
        msg: "Total VMs: {{ requested_vms }}"
   
    - name: Check available hosts count
      set_fact:
        enough_hosts: "{{ available_hosts | length >= requested_vms | int }}"

    - name: Fail if not enough hosts
      fail:
        msg: "Not enough available hosts. Required: {{ requested_vms }}, Available: {{ available_hosts | length }}"
      when: not enough_hosts

    - name: Tag available hosts as busy
      when: enough_hosts
      delegate_to: "{{ item }}"
      become: true
      lineinfile:
        path: /etc/environment
        create: yes
        line: 'OAK_STATUS=free'
      with_items: "{{ available_hosts }}"


    - name: Tag available hosts as free
      when: enough_hosts
      delegate_to: "{{ item }}"
      become: true
      lineinfile:
        path: /etc/environment
        create: yes
        line: 'OAK_STATUS=free'
      with_items: "{{ available_hosts }}"