---
- hosts: "{{ group_workers_full }}"
  roles:
    - kill-all-workers

- hosts: "{{ group_clusters_full }}"
  tasks:
    - name: Set components_path
      set_fact:
        components_path: "/cluster_orchestrator/docker-compose.yml"
    - name: Show oak_repo_path and components_path
      debug:
        msg: "oak_repo_path: {{ oak_repo_path }}, components_path: {{ components_path }}" 

    - name: Include kill-root-cluster
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "cluster_orchestrator/docker-compose.yml"
        oak_repo_path: "{{ oak_repo_path }}"
    - name: Include cleanup-root-cluster  
      include_role:
        name: cleanup-root-cluster
      vars:
        components_path: "cluster_orchestrator/docker-compose.yml"
        oak_repo_path: "{{ oak_repo_path }}"
        oak_net_repo_path: "{{ oak_net_repo_path }}"
 # roles:
 #   - kill-root-cluster
#   - cleanup-root-cluster
#  vars:
#    components_path: "/cluster_orchestrator/docker-compose.yml"
#    oak_repo_path: "{{ oak_repo_path }}"
#    oak_net_repo_path: "{{ oak_net_repo_path }}"
  #tasks:
  #  - name: Kill Cluster components
  #    command: "docker compose -f {{ oak_repo_path }}/cluster_orchestrator/docker-compose.yml  kill"
  #    become: True
  #    when: "{{ group_clusters_full | length > 0 }}"

- hosts: "{{ group_root_full }}"
  tasks:
    - name: Set components_path
      set_fact:
        components_path: "/root_orchestrator/docker-compose.yml"  

    - name: Show oak_repo_path and components_path
      debug:
        msg: "oak_repo_path: {{ oak_repo_path }}, components_path: {{ components_path }}"

    - name: Include kill-root-cluster
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "root_orchestrator/docker-compose.yml"
        oak_repo_path: "{{ oak_repo_path }}"

    - name: Include cleanup-root-cluster
      include_role:
        name: cleanup-root-cluster
      vars:
        components_path: "root_orchestrator/docker-compose.yml"
        oak_repo_path: "{{ oak_repo_path }}"
        oak_net_repo_path: "{{ oak_net_repo_path }}"
 # roles:
 #   - kill-root-cluster
 #   - cleanup-root-cluster
  #  oak_net_repo_path: "{{ oak_net_repo_path }}"
  #tasks:
  #  - name: Kill Root components
  #    command: "docker compose -f {{ oak_repo_path }}/root_orchestrator/docker-compose.yml kill"
  #    become: True
  #    when: "{{ group_root_full | length > 0 }}"
