---
- hosts: localhost
  vars:
      GITHUB_USERNAME: "TheDarkPyotr"
      GITHUB_REPO: "ansible-tests"

  gather_facts: no

  tasks:
    - name: Debug entire extra_vars JSON
      debug:
        msg: |-
          topology_descriptor: {{ topology_descriptor  | to_json }}
         
    - name: Read the JSON file
      slurp:
        src: topology.json
      register: topology_content

    - name: Run the Validator
      command: python3 validator.py "{{ topology_content.content | b64decode }}"
      register: validation_result

    - name: Set environment variable with validation result
      shell: export TOPOLOGY_VALIDITY={{ validation_result.stdout }}
      environment:
        TOPOLOGY_VALIDITY: "{{ validation_result.stdout }}"
      register: env_var_result

    
    - include_tasks: vm_provisioning.yml
      vars:
        topology_desc: "{{ topology_descriptor }}"
        topology_validity: true
        awx_api_url: "http://131.159.25.106"
        awx_username: "admin"
        awx_password: "password"
        busy_vms_group: "busy_vms"
        cmvm_pool_group: "cmvm_pool"


