---
    - name: Parse JSON input
      set_fact:
        topology: "{{ topology_descriptor | to_json}}"

    - name: Check if topology is valid
      fail:
        msg: "Topology is not valid. Deployment cannot proceed."
      when: not topology_is_valid

    - name: Calculate required number of VMs
      set_fact:
        num_clusters: "{{ topology.topology_descriptor.cluster_list | length }}"
        num_nodes: "{{ topology.topology_descriptor.cluster_list | map(attribute='number_of_nodes') | sum }}"
        total_vms: >
          {{ num_clusters + num_nodes + (1 if not (topology.topology_descriptor.one_doc_enabled or topology.topology_descriptor.together_root_cluster) else 0) }}

    - name: Find available VMs in cmvm_pool
      add_host:
        name: "{{ item }}"
        groups: available_vms
      loop: "{{ groups['cmvm_pool'] | difference(groups['busy_vms'] | default([])) }}"
      when: inventory_hostname not in groups['busy_vms'] | default([])
      register: available_vm_list

    - name: Ensure enough available VMs
      fail:
        msg: "Not enough available VMs in cmvm_pool. Required: {{ total_vms }}, Available: {{ available_vm_list.results | length }}"
      when: available_vm_list.results | length < total_vms

    - name: Tag selected VMs
      set_fact:
        selected_vms: "{{ available_vm_list.results | map(attribute='item') | list }}"

    - name: Tag VMs with roles
      add_host:
        name: "{{ selected_vms[item.0] }}"
        groups: deployed_vms
        vm_role: "{{ item.1 }}"
      loop: "{{ (['root'] + ['cluster_' ~ i for i in range(2, num_clusters+1)] + ['worker_' ~ i for i in range(1, num_nodes+1)]) | enumerate }}"

    - name: Create new group with timestamp
      set_fact:
        deploy_group_name: "deploy_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Add selected VMs to new deploy group
      add_host:
        name: "{{ item }}"
        groups: "{{ deploy_group_name }}"
      loop: "{{ groups['deployed_vms'] }}"

    - name: Mark VMs as busy
      set_fact:
        busy_vms: "{{ (groups['busy_vms'] | default([])) + selected_vms }}"
