name: Trigger AWX Job Template

on:
  push:
    branches:
      - main 

jobs:
  trigger-awx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the token
        id: get_token
        env:
          TOWER_USER: ${{ secrets.TOWER_USER }}
          TOWER_PASS: ${{ secrets.TOWER_PASS }}
          TOWER_HOST: ${{ secrets.TOWER_HOST }}
        run: |
          response=$(curl -s -X POST "http://$TOWER_HOST/api/v2/users/1/personal_tokens/" \
            -u "$TOWER_USER:$TOWER_PASS" \
            -H "Content-Type: application/json" \
            --insecure)  # --insecure is equivalent to validate_certs: false in Ansible
          echo "$response" | jq .
          token=$(echo "$response" | jq -r '.token')
          echo "TOWER_API_TOKEN=$token" >> $GITHUB_ENV

      - name: Use the token
        env:
          TOWER_HOST: ${{ secrets.TOWER_HOST }}
          TEMPLATE_ID: "11"
          TOWER_API_TOKEN: ${{ env.TOWER_API_TOKEN }}
        run: |
          response=$(curl -s -X POST "http://$TOWER_HOST/api/v2/job_templates/$(echo $TEMPLATE_NAME)/launch/" \
            -H "Authorization: Bearer $TOWER_API_TOKEN" \
            -H "Content-Type: application/json" \
            --insecure)  # --insecure is equivalent to validate_certs: false in Ansible
          echo "$response" | jq .
