name: API Triggered Workflow

on:
  repository_dispatch:
    types: [ api_call ]  # Replace with your desired event type

jobs:
  api_job:
    runs-on: ubuntu-latest  # Or your preferred runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Extract API Data (Optional)
        # If the API call includes data in the request body, use this step to parse it.
        # Example using jq (if applicable):
        run: |
          data=$(echo '${{ toJson(github.event.client_payload) }}' | jq .)
          echo "Extracted data: $data"

      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
            API_KEY: ${{ secrets.AWX_REPO_API_KEY }}
            MESSAGE: "Test notification from GitHub 🧪"
            TITLE: Testing
            LINK: https://localhost/api/v2/
            SOUND: scifi
            TIME_SENSITIVE: true

